# -*- mode: ruby -*-
# vi: set ft=ruby :

NUM_SKYNET_NODES = 5
FORCE_SKYNET_REBUILD = true
SKYNET_BRANCH = "master"

# This will make chef always deploy the current branch you're working on locally
#SKYNET_BRANCH = (`git branch | grep '*'`).strip.gsub('* ', '')
#


Vagrant::Config.run do |config|
  # bring in the host gopaths, if asked for
  if ENV["VAGRANT_USE_HOST_GOPATH"] then
    gps = ENV["GOPATH"].split(":")
    gpi = 0
    gps.each do |gp| 
      config.vm.share_folder("gp#{gpi}", "/opt/hostgopaths/gp#{gpi}", gp)
      gpi += 1
    end
  end


  # This will be our doozer, and dzns master
  config.vm.define :skynet1 do |c|
    c.vm.box = "lucid64"
    c.vm.network :hostonly, "192.168.126.101"

    c.vm.provision :chef_solo do |chef|
      # This path will be expanded relative to the project directory
      chef.cookbooks_path = "chef/cookbooks"

      chef.json = {
        :skynet_branch => SKYNET_BRANCH,
        :skynet_rebuild => FORCE_SKYNET_REBUILD,
        :skynet_region => 'Chicago',
        :skynet_dzhost => '192.168.126.101:8046',
        :skynet_dznshost => '',
        :skynet_dzdizcover => 'true',
        :skynet_min_port => '9000',
        :skynet_max_port => '9999',
        :skynet_bind_ip => '192.168.126.101',
        :skynet_mgoserver => '192.168.126.101:27017',
        :skynet_mgodb => ''
      }

      chef.add_recipe("apt")
      chef.add_recipe("build-essential")
      chef.add_recipe("mercurial")
      chef.add_recipe("git")
      chef.add_recipe("bzr")
      chef.add_recipe("go")
      chef.add_recipe("mongodb::10gen_repo")
      chef.add_recipe("doozerd")
      chef.add_recipe("skynet")
      chef.add_recipe("skynet::daemon")
      chef.add_recipe("skynet::dashboard")
      chef.add_recipe("skynet::mongo_log")
      chef.add_recipe("skynet::example_service")
      chef.add_recipe("skynet::fibservice")
    end

    # Setup DZNS Master
    c.vm.provision :shell, :inline => "nohup doozerd -timeout 5 -l '192.168.126.101:10000' -w '192.168.126.101:11000' -c 'dzns' 0<&- &> /var/log/dzns.log &" 
    
    # Setup Doozer Master
    c.vm.provision :shell, :inline => "nohup doozerd -timeout 5 -l '192.168.126.101:8046' -w '192.168.126.101:8080' -c 'skynet' -b 'doozer:?ca=192.168.126.101:10000' 0<&- &> /var/log/doozer.log &"

    # Start Daemon
    c.vm.provision :shell, :inline => "nohup /opt/local/gopath/bin/skydaemon --version=1 0<&- &> /var/log/skynet_daemon.log &"

    # Start Dashboard
    c.vm.provision :shell, :inline => "nohup /opt/local/gopath/bin/dashboard -addr 192.168.126.101:80 --webroot=/opt/local/gopath/src/github.com/bketelsen/skynet/cmd/dashboard 0<&- &> /var/log/skynet_dashboard.log &"

    # Start Services
    c.vm.provision :shell, :inline => "sleep 10 && sky --host=192.168.126.101 deploy github.com/bketelsen/skynet/examples/service --version=1"
    c.vm.provision :shell, :inline => "sky --host=192.168.126.101 deploy github.com/bketelsen/skynet/examples/service --version=1"
    c.vm.provision :shell, :inline => "sky --host=192.168.126.101 deploy github.com/bketelsen/skynet/examples/service --version=2"

    c.vm.provision :shell, :inline => "sky --host=192.168.126.101 deploy github.com/bketelsen/skynet/examples/testing/fibonacci/fibservice --version=1"
    c.vm.provision :shell, :inline => "sky --host=192.168.126.101 deploy github.com/bketelsen/skynet/examples/testing/fibonacci/fibservice --version=1"
    c.vm.provision :shell, :inline => "sky --host=192.168.126.101 deploy github.com/bketelsen/skynet/examples/testing/fibonacci/fibservice --version=2"


    # Open additional doozer slots in case we start more nodes
    (NUM_SKYNET_NODES - 1).times do |n|
      i = n + 1
      c.vm.provision :shell, :inline => "printf '' | doozer -a 'doozer:?ca=192.168.126.101:10000' add '/ctl/cal/#{i}'"
      c.vm.provision :shell, :inline => "printf '' | doozer -a 'doozer:?ca=192.168.126.101:8046' -b 'doozer:?ca=192.168.126.101:10000' add '/ctl/cal/#{i}'"
    end

    c.vm.share_folder "skynet", "/opt/skynet", "../"
    #c.vm.share_folder "gopath", "/opt/gopath", ENV['GOPATH']
  end


  # These should all be basically the same
  (NUM_SKYNET_NODES - 1).times do |n|
    i = n + 2

    config.vm.define "skynet#{i}" do |c|
      c.vm.box = "lucid64"
      c.vm.network :hostonly, "192.168.126.10#{i}"

      c.vm.provision :chef_solo do |chef|
        # This path will be expanded relative to the project directory
        chef.cookbooks_path = "chef/cookbooks"

        chef.json = {
          :skynet_branch => SKYNET_BRANCH,
          :skynet_rebuild => FORCE_SKYNET_REBUILD,
          :skynet_region => 'Dallas',
          :skynet_dzhost => "192.168.126.101:8046",
          :skynet_dznshost => '192.168.126.101:10000',
          :skynet_dzdizcover => 'true',
          :skynet_min_port => '9000',
          :skynet_max_port => '9999',
          :skynet_bind_ip => "192.168.126.10#{i}",
          :skynet_mgoserver => '192.168.126.101:27017',
          :skynet_mgodb => ''
        }

        chef.add_recipe("build-essential")
        chef.add_recipe("mercurial")
        chef.add_recipe("git")
        chef.add_recipe("bzr")
        chef.add_recipe("go")
        chef.add_recipe("doozerd")
        chef.add_recipe("skynet")
        chef.add_recipe("skynet::daemon")
        chef.add_recipe("skynet::example_service")
        chef.add_recipe("skynet::fibservice")
      end

      # Setup DZNS Node
      c.vm.provision :shell, :inline => "nohup doozerd -timeout 5 -l '192.168.126.10#{i}:10000' -w '192.168.126.10#{i}:11000' -a '192.168.126.101:10000' -c 'dzns' 0<&- &> /var/log/dzns.log &" 
      #Setup Doozer node
      c.vm.provision :shell, :inline => "nohup doozerd -timeout 5 -l '192.168.126.10#{i}:8046' -w '192.168.126.10#{i}:8080' -c 'skynet' -b 'doozer:?ca=192.168.126.101:10000' 0<&- &> /var/log/doozer.log &"

      # Start Daemon
      c.vm.provision :shell, :inline => "nohup /opt/local/gopath/bin/skydaemon -mgoserver='192.168.126.101:27017' --version=1 0<&- &> /var/log/skynet_daemon.log &"

      # Start Services
      c.vm.provision :shell, :inline => "sleep 15 && sky --host=192.168.126.10#{i} deploy github.com/bketelsen/skynet/examples/service --version=1"
      c.vm.provision :shell, :inline => "sky --host=192.168.126.10#{i} deploy github.com/bketelsen/skynet/examples/service --version=1"
      c.vm.provision :shell, :inline => "sky --host=192.168.126.10#{i} deploy github.com/bketelsen/skynet/examples/service --version=2"

      c.vm.provision :shell, :inline => "sky --host=192.168.126.10#{i} deploy github.com/bketelsen/skynet/examples/testing/fibonacci/fibservice --version=1"
      c.vm.provision :shell, :inline => "sky --host=192.168.126.10#{i} deploy github.com/bketelsen/skynet/examples/testing/fibonacci/fibservice --version=1"
      c.vm.provision :shell, :inline => "sky --host=192.168.126.10#{i} deploy github.com/bketelsen/skynet/examples/testing/fibonacci/fibservice --version=2"


      #c.vm.share_folder "skynet", "/opt/skynet", "../"
      #c.vm.share_folder "gopath", "/opt/gopath", ENV['GOPATH']
    end
  end

  # config.vm.box_url = "http://domain.com/path/to/above.box"
  # config.vm.network :hostonly, "192.168.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
end
